### ISSUE TITLE
SAS AWS Viya quickStart fails

### ISSUE THREAD

**Issue by esshab** [aws-quickstart/quickstart-sas-viya#24] opened 2020-10-14 19:22 UTC
See error below:
2020-10-14 15:18:56 UTC-0400 | SAS-Viya-es002 | CREATE_FAILED | The following resource(s) failed to create: [InternetGateway, VPC, DHCPOptions].
-- | -- | -- | --

**Comment by vsnyc** [comment] 2020-11-02 02:11
@esshab - could you verify that the above wasn't a limits issue in your AWS account?

**Comment by Sketchjar** [comment] 2020-11-02 02:23
I have checked this and there is no limits issue. If you see same code on SASSoftware Github Page.. it shows the changes made to ansible 11 days ago.

**Comment by Sketchjar** [comment] 2020-11-02 02:23
https://github.com/sassoftware/quickstart-sas-viya

https://github.com/sassoftware/quickstart-sas-viya/blob/develop/scripts/ansiblecontroller_prereqs.sh

Version changed to higher version of ansible.

**Comment by vsnyc** [comment] 2020-11-02 02:57
That is correct, there were a couple of issues: https://github.com/aws-quickstart/quickstart-sas-viya/issues/25, and another one related to: `Set DISABLE_JAVA_VALIDATION to use Java vendor 'Red Hat, Inc.' `. Both of them are now fixed in PR: https://github.com/aws-quickstart/quickstart-sas-viya/pull/28. However, the error in those two cases was different, and it was that the AnsibleController couldn't be created. Maybe that's the error in this case as well, but the message in the OP: `The following resource(s) failed to create: [InternetGateway, VPC, DHCPOptions].` didn't indicate that.

If the issue is related to Ansible error or the subsequent error with Java validation, please retry and let me know. I verified both in my personal account as well as in our CI system that the quick start now works.

![Screen Shot 2020-11-01 at 9 56 54 PM](https://user-images.githubusercontent.com/624297/97825607-3203ac00-1c8d-11eb-9d42-a4d87720e869.png)

**Comment by Sketchjar** [comment] 2020-11-02 04:51
Hi, Just tried to run this again. Here is the error:
--------------------------------------------------------------------------------------------------------
Embedded stack arn:aws:cloudformation:us-east-2:628611221169:stack/PRASASVIya-SASViyaStack-1BC8QZMOWDTV8/e97a8d30-1cc5-11eb-b2ce-0a010c4c9e94 was not successfully created: The following resource(s) failed to create: [AnsibleController, StackComplete]

---------------------------------------------------------------------------------------------------------
I am using following Amazon S3 URL for using quickstart. 

https://aws-quickstart.s3.amazonaws.com/quickstart-sas-viya/templates/sas-viya-master.template.yaml

Is there anything which I missing?

**Comment by vsnyc** [comment] 2020-11-03 18:09
Sorry about that, looks like we didn't catch one of the authentication conditions in cfn-init. Currently working on a fix, I'll update the issue when I have a confirmation.

**Comment by Sketchjar** [comment] 2020-11-04 00:08
Thank you, I am eagerly awaiting fix for this. Have to deploy this within our org.

**Comment by vsnyc** [comment] 2020-11-04 02:21
I've verified that the issue has been resolved. See the following commits for details: 
* commit 47efa842006d8a99c766cb93282cfb006bbc4822:    Updated to use regional buckets
* commit b3591b5bb7ecf2ca70cf1178147263e38ab6ea15:    Fixed policy definition
* commit b88c9b9f83c9f26a270cefa89c92f98927d3b2c1:     Updated access policy for Ansible controller
* commit 09eb9ff7c44eb2e492d9e8c0ad7d4b0648daf07b:    Updated cfn-init authentication

To give some context on the failure - we have updated our CI system to use only regional S3 bucket calls to eliminate any Sig V2 requests (see [blog](https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/) for details). When the pull requests #27 and #28 came, to test that within our CI, I had to update the code to 1/ use latest [taskcat](https://aws-quickstart.github.io/taskcat/) for testing and 2/ update all S3 access to go by default to the corresponding regional bucket i.e. `aws-quickstart-<region>`. For the automated testing, we use autogenerated buckets though which passed our testing. 

But if you were launching the code from the default bucket, in my commit: https://github.com/aws-quickstart/quickstart-sas-viya/commit/0274175e35945cfd9f0a6c1e6d39aa427429922b, I missed a few conditions that were resulting in calls to `aws-quickstart` bucket and getting an `access denied error`, since the authorization was to `aws-quickstart-<region>` bucket instead.

Please retry and let me know if you still run into any issues.

**Comment by esshab** [comment] 2020-11-04 02:28
Thanks. Should I use the developer repo or the code has pushed to was.

Esmat Shabon
Sr. Solution Advisor
Fraud and Security Intelligence

Phone: ( 571) 499-1755
Esmat.shabon@sas.com
________________________________

**Comment by vsnyc** [comment] 2020-11-04 02:35
Code has been pushed, you can use the link from the Quick Start page: https://aws.amazon.com/quickstart/architecture/sas-viya/.

**Comment by Sketchjar** [comment] 2020-11-04 04:42
Problem is resolve.

**Comment by vsnyc** [comment] 2020-11-04 05:18
Thanks @Sketchjar, appreciate the confirmation. I'd love to hear about your use case, please feel free to reach me on LinkedIn if you'd like share the details.

**Closed** 2020-11-04 15:54 UTC
